-- CREATE DATABASE faq_database;

CREATE TABLE questions(
  id BIGSERIAL PRIMARY KEY,
  question VARCHAR(300),
  answer VARCHAR(500)
);

-- create table questions (
-- 	id INT,
-- 	question VARCHAR(50),
-- 	answer VARCHAR(50)
-- );
insert into questions (question, answer) values ( 'Mazda', 'B-Series');
insert into questions (id, question, answer) values (2, 'Buick', 'Riviera');
insert into questions (id, question, answer) values (3, 'Lamborghini', 'Murciélago');
insert into questions (id, question, answer) values (4, 'Pontiac', 'GTO');
insert into questions (id, question, answer) values (5, 'Ford', 'Escape');
insert into questions (id, question, answer) values (6, 'Mazda', 'Millenia');
insert into questions (id, question, answer) values (7, 'Isuzu', 'Space');
insert into questions (id, question, answer) values (8, 'Dodge', 'Ram Van B250');
insert into questions (id, question, answer) values (9, 'Mazda', '626');
insert into questions (id, question, answer) values (10, 'Volvo', 'V70');
insert into questions (id, question, answer) values (11, 'Porsche', 'Cayenne');
insert into questions (id, question, answer) values (12, 'MG', 'MGB');
insert into questions (id, question, answer) values (13, 'Cadillac', 'Eldorado');
insert into questions (id, question, answer) values (14, 'Toyota', 'Previa');
insert into questions (id, question, answer) values (15, 'Mitsubishi', 'RVR');
insert into questions (id, question, answer) values (16, 'Mercury', 'Mountaineer');
insert into questions (id, question, answer) values (17, 'Kia', 'Soul');
insert into questions (id, question, answer) values (18, 'Chevrolet', 'Lumina');
insert into questions (id, question, answer) values (19, 'Mazda', 'Tribute');
insert into questions (id, question, answer) values (20, 'Audi', '5000S');
insert into questions (id, question, answer) values (21, 'Ford', 'F150');
insert into questions (id, question, answer) values (22, 'Lexus', 'SC');
insert into questions (id, question, answer) values (23, 'Kia', 'Rio');
insert into questions (id, question, answer) values (24, 'Mercedes-Benz', 'S-Class');
insert into questions (id, question, answer) values (25, 'BMW', 'M5');
insert into questions (id, question, answer) values (26, 'Toyota', 'Sienna');
insert into questions (id, question, answer) values (27, 'Ford', 'E250');
insert into questions (id, question, answer) values (28, 'BMW', '5 Series');
insert into questions (id, question, answer) values (29, 'Mitsubishi', 'Eclipse');
insert into questions (id, question, answer) values (30, 'Pontiac', 'G8');
insert into questions (id, question, answer) values (31, 'Ford', 'Laser');
insert into questions (id, question, answer) values (32, 'Toyota', 'Highlander');
insert into questions (id, question, answer) values (33, 'Nissan', 'Frontier');
insert into questions (id, question, answer) values (34, 'Toyota', 'Tacoma');
insert into questions (id, question, answer) values (35, 'GMC', 'Yukon XL 2500');
insert into questions (id, question, answer) values (36, 'Chevrolet', 'Silverado 1500');
insert into questions (id, question, answer) values (37, 'Lotus', 'Esprit');
insert into questions (id, question, answer) values (38, 'Subaru', 'Forester');
insert into questions (id, question, answer) values (39, 'Lotus', 'Exige');
insert into questions (id, question, answer) values (40, 'Scion', 'tC');
insert into questions (id, question, answer) values (41, 'Toyota', 'Avalon');
insert into questions (id, question, answer) values (42, 'Lincoln', 'Continental Mark VII');
insert into questions (id, question, answer) values (43, 'Mercedes-Benz', 'SL-Class');
insert into questions (id, question, answer) values (44, 'Suzuki', 'Equator');
insert into questions (id, question, answer) values (45, 'Mercury', 'Grand Marquis');
insert into questions (id, question, answer) values (46, 'Land Rover', 'Discovery');
insert into questions (id, question, answer) values (47, 'Subaru', 'Forester');
insert into questions (id, question, answer) values (48, 'Pontiac', 'Grand Prix');
insert into questions (id, question, answer) values (49, 'BMW', '5 Series');
insert into questions (id, question, answer) values (50, 'Ford', 'E150');
insert into questions (id, question, answer) values (51, 'Ford', 'Crown Victoria');
insert into questions (id, question, answer) values (52, 'Buick', 'Park Avenue');
insert into questions (id, question, answer) values (53, 'Dodge', 'Journey');
insert into questions (id, question, answer) values (54, 'BMW', 'Z3');
insert into questions (id, question, answer) values (55, 'Suzuki', 'Grand Vitara');
insert into questions (id, question, answer) values (56, 'GMC', 'Jimmy');
insert into questions (id, question, answer) values (57, 'Toyota', 'FJ Cruiser');
insert into questions (id, question, answer) values (58, 'Cadillac', 'STS');
insert into questions (id, question, answer) values (59, 'BMW', 'M3');
insert into questions (id, question, answer) values (60, 'Mitsubishi', 'Pajero');
insert into questions (id, question, answer) values (61, 'Fiat', '500');
insert into questions (id, question, answer) values (62, 'Toyota', 'Camry Solara');
insert into questions (id, question, answer) values (63, 'Honda', 'Ridgeline');
insert into questions (id, question, answer) values (64, 'Ford', 'Taurus');
insert into questions (id, question, answer) values (65, 'Lexus', 'ES');
insert into questions (id, question, answer) values (66, 'Volkswagen', 'Phaeton');
insert into questions (id, question, answer) values (67, 'Saab', '9-5');
insert into questions (id, question, answer) values (68, 'Volkswagen', 'Jetta');
insert into questions (id, question, answer) values (69, 'Volvo', 'S60');
insert into questions (id, question, answer) values (70, 'Lincoln', 'LS');
insert into questions (id, question, answer) values (71, 'Dodge', 'Ram Van 1500');
insert into questions (id, question, answer) values (72, 'Chevrolet', 'Sportvan G10');
insert into questions (id, question, answer) values (73, 'Toyota', 'RAV4');
insert into questions (id, question, answer) values (74, 'Mercedes-Benz', 'M-Class');
insert into questions (id, question, answer) values (75, 'Buick', 'Skyhawk');
insert into questions (id, question, answer) values (76, 'Audi', 'S4');
insert into questions (id, question, answer) values (77, 'Buick', 'Enclave');
insert into questions (id, question, answer) values (78, 'Mitsubishi', 'Chariot');
insert into questions (id, question, answer) values (79, 'Ford', 'Ranger');
insert into questions (id, question, answer) values (80, 'Chrysler', 'LHS');
insert into questions (id, question, answer) values (81, 'Buick', 'Regal');
insert into questions (id, question, answer) values (82, 'Spyker', 'C8');
insert into questions (id, question, answer) values (83, 'Land Rover', 'Discovery Series II');
insert into questions (id, question, answer) values (84, 'Dodge', 'Caravan');
insert into questions (id, question, answer) values (85, 'Chevrolet', 'Malibu');
insert into questions (id, question, answer) values (86, 'Mazda', '626');
insert into questions (id, question, answer) values (87, 'Ford', 'Mustang');
insert into questions (id, question, answer) values (88, 'Mercury', 'Milan');
insert into questions (id, question, answer) values (89, 'Mazda', 'Millenia');
insert into questions (id, question, answer) values (90, 'Dodge', 'Dakota');
insert into questions (id, question, answer) values (91, 'Volkswagen', 'New Beetle');
insert into questions (id, question, answer) values (92, 'Toyota', 'Paseo');
insert into questions (id, question, answer) values (93, 'Ford', 'Escape');
insert into questions (id, question, answer) values (94, 'Buick', 'Enclave');
insert into questions (id, question, answer) values (95, 'Lotus', 'Elise');
insert into questions (id, question, answer) values (96, 'Suzuki', 'Swift');
insert into questions (id, question, answer) values (97, 'BMW', 'M3');
insert into questions (id, question, answer) values (98, 'Toyota', '4Runner');
insert into questions (id, question, answer) values (99, 'Ford', 'Mustang');
insert into questions (id, question, answer) values (100, 'Porsche', '911');
